# Generated by Django 5.2.5 on 2026-03-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='itemventa',
            options={'ordering': ['venta', 'producto']},
        ),
        migrations.AlterModelOptions(
            name='movimientocuentacorriente',
            options={'ordering': ['-fecha'], 'verbose_name': 'movimiento de cuenta corriente', 'verbose_name_plural': 'movimientos de cuenta corriente'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'ventas'},
        ),
    ]
