# Generated by Django 5.2.5 on 2026-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_cliente_options_alter_itemventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='habilita_cuenta_corriente',
            field=models.BooleanField(default=False),
        ),
    ]
